// <auto-generated />
namespace DocAppBackendWithAuth.Entity.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class FM : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FM));
        
        string IMigrationMetadata.Id
        {
            get { return "201610152012193_FM"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
